a = input('digite algo   ')
print('o tipo primitivo desse valor e',type(a))
print('so tem espaços', a.isspace())
print('é um numero', a.isnumeric())
print('e alfabetico',a.isalpha())
print('e alfanumero', a.isalnum())
print('esta em maiusculo?', a.isupper())
print('esta em minusculo', a.islower())
print('esta capitalizada?', a.istitle())