print(' digite um numero')
n = int(input())
print('o dobro de {} é {}'.format(n, (n *2 )))
print('o triplo de {} é {}'.format(n, (n *3 )))
print('a raiz quadrada de {} é {}'.format(n, (n ** (1/2) )))
