n1 = float(input('nota de matematica:  '))
n2 = float(input('nota de portugues:  '))
n3 = float(input('nota de ciencias:  '))
n4 = float(input('nota de geografia:  '))
n5 = float(input('nota de historia:  '))
n6 = float(input('nota de artes:  '))
n7 = float(input('nota de musica:  '))
n8 = float(input('nota de educacao fisica:  '))
print('a media  entre {}, {}, {}, {} e {} é igual a {}'.format(n1, n2, n3, n4, n5, n1+n2+n3+n4+n5))