print('digite um numero')
nu = int(input())
print('')
print('A tabuada do numero {}'.format(nu))
print('{} x 1 = {}'.format(nu, nu*1))
print('{} x 2 = {}'.format(nu, nu*2))
print('{} x 3 = {}'.format(nu, nu*3))
print('{} x 4 = {}'.format(nu, nu*4))
print('{} x 5 = {}'.format(nu, nu*5))
print('{} x 6 = {}'.format(nu, nu*6))
print('{} x 7 = {}'.format(nu, nu*7))
print('{} x 8 = {}'.format(nu, nu*8))
print('{} x 9 = {}'.format(nu, nu*9))
print('{} x 10 = {}'.format(nu, nu*10))